### ISSUE TITLE
Exception after running

### ISSUE THREAD

**Issue by b-barry** [strongloop/loopback-example-relations#3]
Hello,

I tried to run the sample with "slc run " and got this exception below.
Stroongloop version is 3.0.6  with node version 0.12.0

I don't known how to fix it.

Thank you for your help

``` js
supervisor running without clustering (unsupervised)
Customer created: { name: 'Customer A', age: 21, id: 1 }
Customer created: { name: 'Customer B', age: 22, id: 2 }
Customer created: { name: 'Customer C', age: 23, id: 3 }
Customer created: { name: 'Customer D', age: 24, id: 4 }
Customer created: { name: 'Customer E', age: 25, id: 5 }
Done
Order created: { description: 'Order A', total: 200.45, customerId: 1, id: 1 }
Order created: { description: 'Order B', total: 100, customerId: 1, id: 2 }
Order created: { description: 'Order C', total: 350.45, customerId: 1, id: 3 }
Order created: { description: 'Order D', total: 150.45, customerId: 2, id: 4 }
Order created: { description: 'Order E', total: 10, id: 5 }
done
Review created: { product: 'Product1', star: 3, authorId: 1, id: 1 }
Review created: { product: 'Product2', star: 2, authorId: 2, id: 2 }
Review created: { product: 'Product5', star: 5, id: 3 }
done
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at Server._listen2 (C:\Users\barry.boubacar\Desktop\test\node_modules\loopback\node_modules\continuation-lo
cal-storage\node_modules\async-listener\index.js:71:23)
    at listen (net.js:1155:10)
    at net.js:1253:9
    at dns.js:85:18
    at process._tickDomainCallback (node.js:381:11)
    at process.<anonymous> (C:\Users\barry.boubacar\Desktop\test\node_modules\loopback\node_modules\continuatio
n-local-storage\node_modules\async-listener\index.js:18:15)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
```

**Comment by raymondfeng** [comment]
Most likely, you have another node app running on the same port.

Thanks,

---

Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop http://strongloop.com/ makes it easy to develop APIs http://strongloop.com/mobile-application-development/loopback/ in Node, plus get DevOps capabilities http://strongloop.com/node-js-performance/strongops/ like monitoring, debugging and clustering.

**Comment by superkhau** [comment]
:+1: You probably have another node app using that port.

**Comment by b-barry** [comment]
Yes, sorry for the  issues.
Everything works fine.

Thanks

**Comment by superkhau** [comment]
size 1 (waffle size is bugging out, won't let me size)
